services:
  pdf-to-img:
    build: .
    image: anarkrypto/pdf-to-img
    container_name: pdf-to-img
    ports:
      - "3000:3000"
    environment:
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}